[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  PORT = "5000"
  NODE_ENV = "production"

[environments.development]
  PORT = "5000"
  NODE_ENV = "development"