[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  PORT = "5000"
  NODE_ENV = "production"
  FRONTEND_URL = "https://lambent-biscuit-2313da.netlify.app"
